ais2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('generator/', include('generator.urls')),
    path('admin/', admin.site.urls),
]

generator/urls.py
from django.urls import path
from . import views

app_name = 'generator'
urlpatterns = [
    path('', views.index, name='index'),
    path('help/', views.help, name='help'),
]

generator/models.py
from django.db import models

# Create your models here.

generator/forms.py
from django import forms
from datetime import datetime
import calendar

class DateForm(forms.Form):
    days_in_month = calendar.monthrange(datetime.now().year, datetime.now().month)
    days_list = range(1, days_in_month+1)
    #date_template = forms.CharField(widget=forms.TextInput())
    #dim_list = list(date_template for x in range(1, days_in_month[1]+1))
    #udělat jako dict, nebo list o 2 hodnotach (date a datum)

generator/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
import calendar
from openpyxl import load_workbook
from openpyxl.writer.excel import save_virtual_workbook
from czech_holidays import holidays

import urllib
import json
from django.conf import settings
import requests



# Create your views here.
def help(request):
    return render(request,'generator/help.html')

def index(request):
    days_in_month = calendar.monthrange(datetime.datetime.now().year, datetime.datetime.now().month)
    days_list = range(1, days_in_month[1] + 1)
    first_day_in_m = range(0, datetime.date(datetime.datetime.now().year, datetime.datetime.now().month, 1).weekday())
    if request.method == 'POST':
        # ''' Begin reCAPTCHA validation '''
        # recaptcha_response = request.POST.get('g-recaptcha-response')
        # url = 'https://www.google.com/recaptcha/api/siteverify'
        # values = {
        #     'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
        #     'response': recaptcha_response
        # }
        # data = urllib.parse.urlencode(values).encode()
        # req = urllib.request.Request(url, data=data)
        # response = urllib.request.urlopen(req)
        # result = json.loads(response.read().decode())
        # ''' End reCAPTCHA validation '''

        #použití lib requests
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = request.POST.get('g-recaptcha-response')
        data = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()
        ''' End reCAPTCHA validation '''


        if result['success']:
            # vygeneruje AIS
            vygenerovana_ais = cruncher(dict(request.POST))

            # uloží AIS
            filename = "AIS" + "_" + str(datetime.date(datetime.datetime.now().year, datetime.datetime.now().month, 1))
            response = HttpResponse(save_virtual_workbook(vygenerovana_ais), content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename=%s.xlsx' % filename

            vygenerovana_ais.save(response)
            return response
        else:
            return render(request, 'generator/index.html', {'days_list': days_list, "first_day_in_m": first_day_in_m})

    return render(request, 'generator/index.html', {'days_list': days_list, "first_day_in_m": first_day_in_m})


def cruncher(data_dict):
    """main function to create AIS"""

    # načte šablonu a aktivní list
    wb = load_workbook('generator/AIS_master.xlsx')
    ws = wb.active

    def month_name_cz(month_num):
        month_names = ["leden", "únor", "březen", "duben", "květen", "červen",
                       "červenec", "srpen", "září", "říjen", "listopad", "prosinec"]
        return month_names[month_num - 1]

    # vyplní hlavičku šablony
    ws[
        "A5"] = "pracovní doba:                                                                                   za měsíc: %s" \
                % (month_name_cz(datetime.datetime.now().month) + " " + str(datetime.datetime.now().year))

    # vstupní data
    data = data_dict['date']
    data_clone = data

    # iteruje vstupními daty, modifikuje hodnotu dne po noční službě na "z_or_n1_next"
    for day_num, day in enumerate(data_clone):
        if day in ["z", "n1"] and day_num+1 != len(data_clone):
            data_clone[day_num + 1] = "z_or_n1_next"
    data = data_clone

    day_obj_list = []

    class Day():
        """objekt reprezentující každý den v měsící"""

        def __init__(self, day_num, occupation):
            self.day_num = day_num + 1  # number of the day in the month.
            self.occupation = occupation  # ev. "služba" at given day -d1,d2,d3,z,n1

            # today = datetime.date()
            self.date = datetime.date(datetime.datetime.now().year, datetime.datetime.now().month, self.day_num)
            self.den_v_tydnu = self.date.weekday()
            self.svatek = self.date in holidays
            self.vikend = self.den_v_tydnu >= 5
            # self.post_night_shift = False

            self.input = []
            self.to_iter = []

        def populator(self, ais_workbook_ws):
            """funkce, která podle charakteristik objektu vyplňuje šablonu AIS"""

            if self.occupation in ["d1", "d2"]:
                if self.vikend and not self.svatek:
                    self.input = [" 07:00", "19:00", 12, 12, 12]
                    self.to_iter = ["C", "D", "J", "R", "T"]
                elif self.svatek and not self.vikend:
                    self.input = [" 07:00", "19:00", 12, 12, 12]
                    self.to_iter = ["C", "D", "J", "O", "U"]
                elif self.vikend and self.svatek:
                    self.input = [" 07:00", "19:00", 12, 12, 12, 12]
                    self.to_iter = ["C", "D", "J", "R", "T", "U"]
                else:
                    self.input = [" 07:00", "19:00", "11:30", "12:00", 11.5, 3.5]
                    self.to_iter = ["C", "D", "E", "F", "J", "O"]
            elif self.occupation == "d3":
                if self.svatek and self.vikend:
                    self.input = [" 07:00", "19:00", 4, 4, 4, 4]
                    self.to_iter = ["C", "D", "J", "R", "T", "U"]
                elif self.svatek and not self.vikend:
                    self.input = [" 07:00", "19:00", 4, 4, 4]
                    self.to_iter = ["C", "D", "J", "O", "U"]
                else:
                    self.input = [" 07:00", "11:00", 4, 4, 4]
                    self.to_iter = ["C", "D", "J", "R", "T"]

            elif self.occupation in ["z", "n1"]:
                if self.vikend and not self.svatek:
                    self.input = [" 19:00", "00:00", 5, 5, 2, 5]
                    self.to_iter = ["C", "D", "J", "R", "S", "T"]
                elif self.svatek and not self.vikend:
                    self.input = [" 19:00", "00:00", 5, 5, 2, 5]
                    self.to_iter = ["C", "D", "J", "O", "S", "U"]
                elif self.vikend and self.svatek:
                    self.input = [" 19:00", "00:00", 5, 5, 2, 5, 5]
                    self.to_iter = ["C", "D", "J", "R", "S", "T", "U"]
                else:
                    self.input = [" 07:00", "00:00", "11:00", "19:00", 9, 2]
                    self.to_iter = ["C", "D", "E", "F", "J", "S"]
            elif self.occupation == "z_or_n1_next":
                if self.vikend and not self.svatek:
                    self.input = [" 00:00", "07:00", 7, 7, 6, 7]
                    self.to_iter = ["C", "D", "J", "R", "S", "T"]
                elif self.svatek and not self.vikend:
                    self.input = [" 00:00", "07:00", 7, 7, 6, 7]
                    self.to_iter = ["C", "D", "J", "O", "S", "U"]
                elif self.vikend and self.svatek:
                    self.input = [" 00:00", "07:00", 7, 7, 6, 7, 7]
                    self.to_iter = ["C", "D", "J", "R", "S", "T", "U"]
                else:
                    self.input = [" 00:00", "07:00", 7, 6]
                    self.to_iter = ["C", "D", "J", "S"]
            elif self.occupation == "nan":
                if self.vikend and not self.svatek:
                    self.input = []
                    self.to_iter = []
                elif self.svatek and not self.vikend:
                    self.input = [" 07:00", "15:30", "11:30", "12:00", 8]
                    self.to_iter = ["C", "D", "E", "F", "J"]
                elif self.vikend and self.svatek:
                    self.input = []
                    self.to_iter = []
                else:
                    self.input = [" 07:00", "15:30", "11:30", "12:00", 8]
                    self.to_iter = ["C", "D", "E", "F", "J"]

            # Proveden změny v šabloně pro daný den.
            for column_num in range(len(self.to_iter)):
                sel_cell = self.to_iter[column_num] + str(20 + self.day_num)
                ais_workbook_ws[sel_cell] = self.input[column_num]

    for data_index in range(len(data)):
        day_obj_list.append(Day(data_index, data[data_index]))

    for day_obj in day_obj_list:
        day_obj.populator(ws)

    # wb.save("sample.xlsx")

    # uloží file na disk uživatele
    # response = HttpResponse(excel_file.read(),
    #                         content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    #
    # # set the file name in the Content-Disposition header
    # response['Content-Disposition'] = 'attachment; filename=%s.xlsx' % normal_filename

    # response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    # response['Content-Disposition'] = 'attachment; filename=mymodel.xlsx'

    # response = HttpResponse(save_virtual_workbook(wb), content_type='application/vnd.ms-excel')

    # wb.save(response)
    return wb

generator/templates/generator/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My amazing site{% endblock %}</title>
    <style>
        .datum {
            text-align: center;
        }

        * {
            box-sizing: border-box;
            padding: 0;
            margin: 0;
        }

        html, body {
            width: 60%;
            height: 100%;
            margin: 0 auto;
            padding: 0 0;
            text-transform: none;
            text-align: center;
            background: #d7ecff;
            color: #0F6A8B;
        }

        .grid {
            display: grid;
            grid-template-columns: auto auto auto;
            grid-template-rows: 45px auto 45px;
            grid-gap: 0;
            min-height: 100%;

        }

        header, footer, article {
            grid-column: 1 / 4;
        }

        @media all and (max-width: 700px) {
            aside,
            article {
                grid-column: 1 / 4;
            }
        }

        /* Demo Specific Styles */

        header {
            padding-top: 0px;
            background: #354ae6;
        }

        footer {
            background: #2f263a;
            padding-top: 10px;
            color: white;
        }

        article {
            background: #c2cad5;
            align-items: center;
            justify-content: center;
            text-align: left;
            padding-top: 50px;
            padding-left: 25px;
            padding-right: 25px;
        }

        ul.menu {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        li.menu-li {
            float: left;
        }

        li:last-child {
        }

        li.menu-li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li.menu-li a:hover:not(.active) {
            background-color: #111;
        }

        .active {
            background-color: #0F6A8B;
        }

        .box {
            background-color: #444;
            color: #fff;
            border-radius: 5px;
            padding: 1px;
            font-size: 100%;
            text-align: center;
        }

        .box_inactive {
            background-color: #9a9a9a;
            color: #fff;
            border-radius: 5px;
            padding: 1px;
            font-size: 100%;
            text-align: center;
            vertical-align: middle;
        }

        .box > input[type=submit] {
            width: 75px;
            border-radius: 5px;
        }

        .box_submit {
            width: 75px;
            border-radius: 5px;
        }

        .box:hover {
            background-color: #7f7f7f;
        }

        .wrapper_box {
            width: 430px;
            margin: 0 auto;
            padding: 10px;
            display: grid;
            grid-gap: 10px;
            grid-template-columns: repeat(7, 50px);
            grid-template-rows: 50px 50px 50px 50px 50px 50px 50px;
            grid-auto-flow: row;
            background-color: antiquewhite;
            border-radius: 3px 3px 0px 0px;
        }

        select {
            width: 80%;
            border: none;
            border-radius: 4px;
            background-color: #f1f1f1;
        }

        .recaptcha {
            width: 430px;
            margin: 0 auto;
            padding: 10px;
            display: grid;
            grid-gap: 10px;
            grid-auto-flow: row;
            background-color: antiquewhite;
            border-radius: 0px 0px 3px 3px;
        }

    </style>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
<div class="grid">
    <header>
        <ul class="menu">
            <li class="menu-li"><a class="active" href="{% url 'generator:index' %}">
                <div>
                    <p>Generátor AIS</p><br>
                </div>
            </a></li>
            <li class="menu-li"><a href="{% url 'generator:help' %}">návod</a></li>
            <li class="menu-li"><a href="#contact">Contact</a></li>
            <li class="menu-li" style="float:right"><a href="#about">About</a></li>
        </ul>
    </header>


    <article>
        {% block content %}{% endblock %}
    </article>


    <footer>
        <h5>Jan Bortel 2018</h5>
    </footer>
</div>
</body>
</html>

generator/templates/generator/help.html
{% extends "generator/base.html" %}

{% block content %}
<h5>Postup</h5><br>
    <ul>
        <li>Generátor je nastavený vždy na aktuální měsíc.</li>
        <li>V příslušném poli pro den vaší služby vyberte její typ.</li>
        <li>Zaškrtněte, že jste člověk a ev. to dokažte na úloze, která po vás bude vyžadována :)</li>
        <li>Klikněte na "Generovat"</li>
        <li>Zjeví se nabídka k uložení vygenerované AIS</li>
        <li>Tu si uložte, otevřete a doplňe o další potřebné údaje (jméno, os. číslo, etc.)</li>
        <li>Pozn.: stránka optimalizována pro prohlížeče Chrome a Edge, v Internet Exploreru nefunguje její rozložení, ale generovácí funkce je zachována</li>
    </ul>
    <br>
    <p>
    Je pravděpodobné, že něco někde nebude fungovat, stránka je stále ve fázi testování. Rovněž je samozřejmé, že neručím
    za správnost vygenerovaných dat, chybička se může kdykoliv vloudit, proto prosím svou AIS před odevzdáním zkontrolujte.
    </p>

{% endblock %}

generator/templates/generator/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" novalidate>
  {% csrf_token %}
  <table border="1">
    {{ form }}
  </table>
  <button type="submit">Submit</button>
</form>
</body>
</html>

generator/templates/generator/index.html
{% extends "generator/base.html" %}

{% block content %}
    <h1 class="datum"> {% now "F Y" %}</h1><br>
    <form action="{% url 'generator:index' %}" method="post">
     {% csrf_token %}
        <div class="wrapper_box">
            <div class="box_inactive">Po</div>
            <div class="box_inactive">Út</div>
            <div class="box_inactive">St</div>
            <div class="box_inactive">Čt</div>
            <div class="box_inactive">Pá</div>
            <div class="box_inactive">So</div>
            <div class="box_inactive">Ne</div>
            {% for foo in first_day_in_m %}
                <div class="box_inactive"></div>
            {% endfor %}

            {% for day in days_list %}
                <div class="box">
                    {% comment %}<input type="text" name="date" id="date {{ forloop.counter }} "><br>
                <label for="date {{ forloop.counter }} ">{{ day }}</label>{% endcomment %}
                    <select id="date {{ forloop.counter }} " name="date">
                        <option value="nan"></option>
                        <option value="d1">D1</option>
                        <option value="d2">D2</option>
                        <option value="z">Z</option>
                        <option value="n1">N1</option>
                        <option value="d3">D3</option>
                    </select>
                    <label for="date {{ forloop.counter }} ">{{ day }}</label>
                </div>
            {% endfor %}
            <br>

        </div>
        <div class="recaptcha">
            <div class="g-recaptcha" data-sitekey="6LcBYncUAAAAANJxrHi-15DFKZPyNdP9bVmYwrrl"></div>
            <br>
            <input class="box_submit" type="submit" value="Generovat "><br>
        </div>
    </form>

{% endblock %}